services:
  mysql:
    image: mysql:8.4
    container_name: ospp-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: ospp_project
    ports:
      - "3306:3306"

  server:
    build: .
    container_name: ospp-server
    depends_on:
      - mysql
    ports:
      - "8081:8080"
    environment:
      SPRING_DOCKER_COMPOSE_ENABLED: false
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/ospp_project?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234